[tool.black]
line-lenght = 100
target-version = ["py310"]
extend-exclude = "frontend"

[tool.isort]
profile = "black"
line_length = 100
py_version = 310
skip_gitignore = true
atomic = true
skip = ["frontend"]

[tool.pytest.ini_options]
python_files = "tests/*"
addopts = "--cov"

[tool.coverage.run]
branch = true
source = ["videoshare"]
omit = []

[tool.mypy]
files = "."
exclude = ["frontend", "migrations", "tests", "venv"]
warn_return_any = true
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
no_implicit_optional = true
warn_redundant_casts = true
disallow_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
pretty = true
